import localFont from 'next/font/local';
import "./styles/global.css";
import HeaderSwitcher from './components/HeaderSwitcher'
import Footer from './components/Footer/footer'

const geist = localFont({
  src: [
    {
      path: '../fonts/Geist-Regular.ttf',
      weight: '400', 
      style: 'normal',
    },
    {
      path: '../fonts/Geist-SemiBold.ttf',
      weight: '600', 
      style: 'normal',
    },
    {
      path: '../fonts/Geist-Medium.ttf',
      weight: '500',
      style: 'normal',
    }

  
  ],
  variable: '--font-geist',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk" className={geist.variable}>
      <body>
        <HeaderSwitcher />
        <main>{children}</main>
         <Footer />
      </body>
    </html>
  )
}